### ISSUE TITLE
Investigations instead of Dataset

### ISSUE THREAD

**Issue by manonromain** [alephdata/alephclient#37]
Hi there, 

When uploading my ftm dataset to aleph, I use: 

```ftm store iterate -d NAME_DATASET | alephclient write-entities -f NAME_IN_ALEPH```

I also tried the following, both with `"casefile"=True` and  `"casefile"=False` 

```
api = AlephAPI()
options = {"casefile": False}
collection = api.load_collection_by_foreign_id(my_aleph_dataset, options)
# collection = api.load_collection_by_foreign_id(my_aleph_dataset)
cid = collection.get('id')

# FTM Store
dataset = get_dataset(my_dataset)
api.write_entities(cid, dataset.iterate())
```

In all cases, the result is an Investigation containing all my entities is created in Aleph UI, but I would rather have a Dataset instance, like my coworkers. 

I tried the exact same code on another computer, with the same dataset and same alephclient version, and it creates a dataset instance on their Aleph UI. Can you help me understand how to fix it?

Best,

**Comment by brrttwrks** [comment]
Currently, only an admin of an Aleph instance can make a dataset or change an investigation into a dataset. If you were an admin of your own Aleph, then you could do something like:

```
from alephclient import api

api = api.AlephAPI()
foreign_id = "testy_mctesticals"
options = { "casefile": False }
collection = api.load_collection_by_foreign_id(foreign_id, options)
```
However, if you are not an admin, then that won't do anything. 

Why is this the case? Datasets in Aleph are considered evidentiary and are immutable. They are for reference and their source is an official site, a leak, or a source. This is not something we would want to change. Otherwise, how could we reference it in a story if we couldn't fix its provenance and guarantee it hasn't been altered?

In some cases, we can decide to change an investigation into a dataset, thereby making it immutable from that point on. This is usually to calcify the data once it gets to a point where it itself becomes a reference for other investigations for some reason.

**Comment by sunu** [comment]
Hi @manonromain, I am closing this issue for now. Feel free to reopen if you have any more questions or suggestions.
