### ISSUE TITLE
Stream entities: filter by schema doesn't appear to work

### ISSUE THREAD

**Issue by adri0** [alephdata/alephclient#40]
I noticed there's a parameter `--schema` for `stream-entities` command, but it seems to always all entities for the given collection as output regardless of what has been provided. 

The API documentation doesn't mention this parameters for the `_stream` function anyway. Is it the client that is outdated in relation to the API, or could it be the case that the Aleph instance or its database I'm trying to reach is misconfigured?

**Comment by sunu** [comment]
I think the api documentation are incomplete in this case. The `_stream` api endpoint does support schema as a parameter: https://github.com/alephdata/aleph/blob/5663e30d9138c2ff3137caf40a9afbdca896223d/aleph/views/stream_api.py#L46

The response will contain all entities that are of the given schema or inherit from that given schema. For example, if you stream LegalEntities, you'll also get back Persons, Companies, PublicBodies and so on since they inherit their schema from LegalEntity.

If that is not the case, then we should investigate further.

**Comment by adri0** [comment]
Got it. I understand it now that when provided a schema it also return its children schemas, which totally makes sense. In that case it seems to be working fine.
